name: iti_freelancing_hub
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  cupertino_icons: ^1.0.8
  dio: null
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_launcher_icons: ^0.14.3
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.7
  image_picker: ^1.1.2
  intl: ^0.20.2
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  fluttertoast: ^8.2.2
  conditional_builder_rec: 
  another_flushbar:
  url_launcher: ^6.3.1
  

dev_dependencies:
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_assets:
  assets_path: assets/images
  output_path: lib/core/utils/images
  filename: app_images.dart
